#!/bin/sh

set -e

IMAGE_NAME=bitnami/kubectl
IMAGE_VERSION=1.23.6-debian-10-r20

mkdir -p "$HOME/.kube"
docker run --rm -it --user "$(id -u)":"$(id -g)" --net=host -v "$HOME/.kube:/.kube" $IMAGE_NAME:$IMAGE_VERSION "$@"