#!/bin/sh

set -e

. "$(dirname "$0")/lib/clean.sh"
. "$(dirname "$0")/lib/stop.sh"

CONTAINER_NAME=mariadb
VOLUME_NAME=mariadb
IMAGE_NAME=mariadb
IMAGE_VERSION=10.7.3-focal
HOST_PORT=3306
MARIADB_ROOT_PASSWORD=root

start() {
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "$CONTAINER_NAME is already running"
        exit 1
    fi

    docker run --rm -d --name $CONTAINER_NAME -e MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD -p $HOST_PORT:3306 -v $VOLUME_NAME:/var/lib/mysql $IMAGE_NAME:$IMAGE_VERSION > /dev/null 2>&1
    echo "$CONTAINER_NAME started at http://localhost:$HOST_PORT, username: root, password: $MARIADB_ROOT_PASSWORD"
}

if [ "$1" = "stop" ]; then
    stop
fi

if [ "$1" = "start" ]; then
    start
fi

if [ "$1" = "clean" ]; then
    clean
fi

if [ $# -eq 0 ]; then
    start
fi