#!/bin/sh

set -e

. "$(dirname "$0")/lib/stop.sh"

CONTAINER_NAME=memcached
IMAGE_NAME=memcached
IMAGE_VERSION=1.6.15-alpine3.15
HOST_PORT=11211

start() {
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "$CONTAINER_NAME is already running"
        exit 1
    fi

    docker run --rm -d --name $CONTAINER_NAME -p $HOST_PORT:11211 $IMAGE_NAME:$IMAGE_VERSION > /dev/null 2>&1
    echo "$CONTAINER_NAME started at http://localhost:$HOST_PORT"
}

if [ "$1" = "stop" ]; then
    stop
fi

if [ "$1" = "start" ]; then
    start
fi

if [ $# -eq 0 ]; then
    start
fi