#!/bin/sh

set -e

. "$(dirname "$0")/lib/logs.sh"
. "$(dirname "$0")/lib/stop.sh"

CONTAINER_NAME=nats-server
IMAGE_NAME=nats
IMAGE_VERSION=2.8.2-alpine3.15
HOST_PORT_1=4222
HOST_PORT_2=6222
HOST_PORT_3=8222

start() {
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "$CONTAINER_NAME is already running"
        exit 1
    fi

    docker run --rm -d --name $CONTAINER_NAME -p $HOST_PORT_1:4222 -p $HOST_PORT_2:6222 -p $HOST_PORT_3:8222 $IMAGE_NAME:$IMAGE_VERSION > /dev/null 2>&1
    echo "$CONTAINER_NAME started at localhost, listening on client port $HOST_PORT_1, cluster port $HOST_PORT_2 and monitorint port $HOST_PORT_3."
}

if [ "$1" = "stop" ]; then
    stop
fi

if [ "$1" = "start" ]; then
    start
fi

if [ "$1" = "logs" ]; then
    logs "$@"
fi

if [ $# -eq 0 ]; then
    start
fi