#!/bin/sh

set -e

IMAGE_NAME=postgres
IMAGE_VERSION=14.2-bullseye

docker run --rm -it --user "$(id -u)":"$(id -g)" --net=host -v "$(pwd)":/postgres -w /postgres $IMAGE_NAME:$IMAGE_VERSION pg_dump "$@"