#!/bin/sh

set -e

. "$(dirname "$0")/lib/stop.sh"

CONTAINER_NAME=phpmyadmin
IMAGE_NAME=phpmyadmin
IMAGE_VERSION=5.1.3-apache
HOST_PORT=8082

start() {
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "$CONTAINER_NAME is already running"
        exit 1
    fi

    docker run --rm -d --name $CONTAINER_NAME -e PMA_ARBITRARY=1 -p $HOST_PORT:80 $IMAGE_NAME:$IMAGE_VERSION > /dev/null 2>&1
    echo "$CONTAINER_NAME started at http://localhost:$HOST_PORT"
}

if [ "$1" = "stop" ]; then
    stop
fi

if [ "$1" = "start" ]; then
    start
fi

if [ $# -eq 0 ]; then
    start
fi
