#!/bin/sh

set -e

. "$(dirname "$0")/lib/clean.sh"
. "$(dirname "$0")/lib/logs.sh"
. "$(dirname "$0")/lib/stop.sh"

CONTAINER_NAME=redis
VOLUME_NAME=redis
IMAGE_NAME=redis
IMAGE_VERSION=7.0.5-alpine3.16
HOST_PORT=6379

start() {
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "$CONTAINER_NAME is already running"
        exit 1
    fi

    docker run --rm -d --name $CONTAINER_NAME -p $HOST_PORT:6379 -v $VOLUME_NAME:/data $IMAGE_NAME:$IMAGE_VERSION --save 60 1 1> /dev/null
    echo "$CONTAINER_NAME started on localhost, listening on port $HOST_PORT"
}

if [ "$1" = "stop" ]; then
    stop
fi

if [ "$1" = "start" ]; then
    start
fi

if [ "$1" = "clean" ]; then
    clean
fi

if [ "$1" = "logs" ]; then
    logs "$@"
fi

if [ $# -eq 0 ]; then
    start
fi
